# -*- coding: utf-8 -*-

from detectron2.config import CfgNode as CN


def add_spatiotemporal_config(cfg):
    """
    Add config for spatiotemporal.
    """
    _C = cfg

    _C.DATALOADER.TRAIN_GROUPS_PER_VIDEO = 10
    _C.DATALOADER.TRAIN_SUBSAMPLING = True

    _C.MODEL.SPATIOTEMPORAL = CN()
    _C.MODEL.SPATIOTEMPORAL.NUM_FRAMES = 1
    # With FORWARD_AGGREGATION=True, it process 2*NUM_FRAMES + 1
    # (f_{t-NUM_FRAMES}, ..., f_{t-1}, f_t, f_{t+1}, ..., f_{t+NUM_FRAMES})
    _C.MODEL.SPATIOTEMPORAL.TEMPORAL_DROPOUT = False
    _C.MODEL.SPATIOTEMPORAL.FORWARD_AGGREGATION = False
    _C.MODEL.SPATIOTEMPORAL.ST_CLS = True
    _C.MODEL.SPATIOTEMPORAL.SPATIAL_CLS = True
    _C.MODEL.SPATIOTEMPORAL.FREEZE_PROPOSAL_GENERATOR = False
    _C.MODEL.SPATIOTEMPORAL.FREEZE_SPATIAL_HEAD = False
    # BACKBONE.FREEZE_AT do not freeze lateral connections
    _C.MODEL.SPATIOTEMPORAL.FREEZE_BACKBONE = False
    _C.MODEL.SPATIOTEMPORAL.ST_POOLER_TYPE = "ROIAlignV2"
    
    _C.MODEL.SPATIOTEMPORAL.ST_CLS_SHORT_TERM_AGGREGATION = True

    _C.MODEL.TUBELET_AGGREGATION_HEAD = CN()
    _C.MODEL.TUBELET_AGGREGATION_HEAD.NAME = "MaxPoolAggregationHead"

    # Attention head
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD = CN()
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.NAME = "FastRCNNConvFCHead"
    
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION = CN()
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION.EMBED_DIM = 64
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION.GROUP = 16
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION.STAGE = 2
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION.ADVANCED_STAGE = 0
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.ATTENTION.LOCATION_FREE = False

    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.REF_POST_NMS_TOP_N = 75
    _C.MODEL.SPATIOTEMPORAL.ROI_BOX_HEAD.RDN_RATIO = 0.2
    
    # Long-term
    _C.MODEL.SPATIOTEMPORAL.LONG_TERM = False
    _C.MODEL.SPATIOTEMPORAL.NUM_KEYFRAMES = 1
    _C.MODEL.SPATIOTEMPORAL.KEYFRAME_INTERVAL = 1
    _C.MODEL.SPATIOTEMPORAL.PROPOSAL_TRACKING = False
    _C.MODEL.SPATIOTEMPORAL.TEST_TRACKING_TYPE = "replace"


    _C.INPUT.RANDOM_FLIP = True